kind: Provider
id: nware.provider.mock.ktea-update
source:
  note_url: https://raw.githubusercontent.com/eivindml/template-release-note/master/README.md
  version: 2.0.0

---

kind: Provider
id: nware.provider.mock.injection
source:
  chart: 
    foo: bar
  inlines: 
    bar: baz

---

kind: Provider
id: nware.provider.mock.initial-injection
source:
  chart: {}
  inlines: {}