substitutions:
  _IMG_FQDN: "us-central1-docker.pkg.dev/nectar-bazaar/public/ice-kream-app"
  _V1_TAG: 1.0.0
  _V2_TAG: 2.0.0

timeout: 900s

images:
  - "${_IMG_FQDN}:latest"
  - "${_IMG_FQDN}:${_V1_TAG}"
  - "${_IMG_FQDN}:${_V2_TAG}"

steps:
  - id: "Pull previous"
    name: gcr.io/cloud-builders/docker
    waitFor: []
    entrypoint: "bash"
    args:
      - "-c"
      - |-
        docker pull ${_IMG_FQDN}:latest || exit 0;

  - id: "Build image"
    name: gcr.io/cloud-builders/docker
    waitFor:
      - "Pull previous"
    args:
      - "build"
      - "."
      - "--cache-from"
      - "${_IMG_FQDN}:latest"
      - "-t"
      - "${_IMG_FQDN}:latest"
      - "-t"
      - "${_IMG_FQDN}:${_V1_TAG}"
      - "-t"
      - "${_IMG_FQDN}:${_V2_TAG}"
