#kind: ManifestVariableDependency
#id: variable_dependency.template.hpa_disabled
#effect: prevents_read
#info: HPA-specific configurations ignored if HPA is disabled
#active:
#  kind: Predicate
#  challenge: get::self>>from_variable>>current_value
#  operator: true
#
#---
#
#kind: ManifestVariableDependency
#id: variable_dependency.template.ingress_disabled
#effect: prevents_read
#info: Ingress-specific configurations ignored if Ingress is disabled
##info: Something about ingress yo
#active:
#  kind: Predicate
#  challenge: get::self>>from_variable>>current_value
#  operator: falsiness
