kind: ManifestVariable
id: quotas.requests.cpu
info: "The sum of Nectar Hub's workloads' CPU requests cannot exceed this value"
input:
  kind: SliderInput
  min: 100
  max: 1300
  step: 100
  suffix: m

---

kind: ManifestVariable
id: quotas.requests.memory
info: "The sum of Nectar Hub's workloads' memory requests cannot exceed this value"
input:
  kind: SliderInput
  min: 0.5
  max: 1.3
  step: 0.1
  suffix: Gi

---

kind: ManifestVariable
id: quotas.limits.cpu
info: "The sum of Nectar Hub's workloads' CPU limits cannot exceed this value"
input:
  kind: SliderInput
  min: 200
  max: 2000
  step: 100
  suffix: m

---

kind: ManifestVariable
id: quotas.limits.memory
info: "The sum of Nectar Hub's workloads' cpu requests cannot exceed this value"
input:
  kind: SliderInput
  min: 0.5
  max: 1.3
  step: 0.1
  suffix: Gi
