kind: Operation
id: nmachine.prom.operation.locate-existing-server
title: Locate an existing Prometheus Server
info: "Point the application to a Prometheus server that is already
or is capable of monitoring the application"
synopsis: assets::locate-existing-server.md
tags: ['monitoring']
labels:
  public: true
stages:
  - id::sdk.stage.monitoring

---

id: sdk.misc.ping-monitoring-server
kind: MultiAction
sub_actions:
  - sdk.action.commit_step_values_action
  - kind: RunPredicatesAction
    title: Try to reach monitoring server
    info: Send HTTP to ${endpoint}
    endpoint: get::sdk.supplier.config.prefs .monitoring.url

---

kind: Stage
id: sdk.stage.monitoring
title: Locate Monitoring Server
info: "If you have a monitoring service inside
 or outside in your cluster,
you can point this application to it in order to give
Nectar data capabilities"

steps:
  - id: sdk.step.monitoring-step-1
    title: Set Type & Location
    info: "State whether the server is inside or outside
    the cluster, and point to it."
    synopsis: assets::locate-existing-server.md

    commit:
      standard:
        kind: MergeSupplier
        source: [get::props default_commit->.standard, {enabled: true}]
    action:
      kind: MultiAction
      inherit: sdk.action.step_apply_application_manifest_e2e_action
      config_space: nmachine.prom

    fields:
      - id::access_type
      - id::url
      - id::service_namespace
      - id::service_name

    summary_desc: get::nmachine.prom.locate_op_summary