release: 0.0.0
namespace: default

deployment:
  image: us-central1-docker.pkg.dev/nectar-bazaar/public/ice-cream-app:2.0.0
  replicas: 1
  version: none
  flavor: vanilla

service:
  name: ice-cream
  port: 8080
  type: ClusterIP

quotas:
  enabled: false
  requests:
    cpu: 900m
    memory: 2Gi
  limits:
    cpu: 900m
    memory: 2Gi

telem_storage:
  strategy: managed_pvc
  host: telem-redis
  port: 6379