kind: Operation
id: "app.operation.enable-ingress"
synopsis: "assets::enable-ingress-synopsis.md"
stages:
  - kind: Stage
    id: "app.stage.enable-ingress.main"
    steps:
      - id: "app.step.enable-ingress.main.main"
        title: ""
        synopsis: "assets::enable-ingress-synopsis.md"
        fields:
          - variable: "id::ingress.routes.monolith.host"