timeout: 1200s

substitutions:
  _IMG_BASE: us-central1-docker.pkg.dev/nectar-bazaar/public/kerbi2api

images:
  - ${_IMG_BASE}:${TAG_NAME}
  - ${_IMG_BASE}:latest

steps:
  - id: "Build image"
    waitFor: []
    name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "."
      - "-t"
      - ${_IMG_BASE}:${TAG_NAME}
      - "-t"
      - ${_IMG_BASE}:latest
