apiVersion: v1
kind: Secret
metadata:
  namespace: ice-kream
  name: db-creds
  labels:
    app: ice-kream
data:
  db_password: dW5zYWZl

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: ice-kream
  finalizers: []
  labels:
    app: ice-kream
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ice-kream
  name: postgres
  labels:
    app: ice-kream
    microservice: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ice-kream
      microservice: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: ice-kream
        microservice: postgres
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres:9.6-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: database
          subPath: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: db_password
              optional: true
        - name: POSTGRES_DB
          value: mosaic-postgres
        - name: PGDATA
          value: "/var/lib/postgresql/data"

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: ice-kream
  labels:
    app: ice-kream
    microservice: postgres
spec:
  type: ClusterIP
  selector:
    app: ice-kream
    microservice: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ice-kream
  name: monolith
  labels:
    app: ice-kream
    microservice: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ice-kream
      microservice: monolith
  template:
    metadata:
      labels:
        app: ice-kream
        microservice: monolith
    spec:
      initContainers:
      - name: db-init
        image: us-central1-docker.pkg.dev/nmachine/public/ice-kream:0.0.1
        imagePullPolicy: Always
        command:
        - bundle
        - exec
        - rake
        - db:init
        ports:
        - containerPort: 3000
        resources: 
        env:
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: ICE_KREAM_VER
          value: 0.0.1
        - name: ADMIN_EMAIL
          value: admin@admin.com
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: '5432'
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: db_password
              optional: true
        - name: SECRET_KEY_BASE
          value: 7bb0f08664366f0f5a525fde0e90e333deecfb133775f0f88bf0d84f754121d171abe7a19554102be0b594bd414254122874acc8fd0454f5d155754def22a599
      containers:
      - name: main
        image: us-central1-docker.pkg.dev/nmachine/public/ice-kream:0.0.1
        imagePullPolicy: Always
        command:
        - bundle
        - exec
        - rails
        - server
        ports:
        - containerPort: 3000
        resources: 
        env:
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: ICE_KREAM_VER
          value: 0.0.1
        - name: ADMIN_EMAIL
          value: admin@admin.com
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: '5432'
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: db_password
              optional: true
        - name: SECRET_KEY_BASE
          value: 7bb0f08664366f0f5a525fde0e90e333deecfb133775f0f88bf0d84f754121d171abe7a19554102be0b594bd414254122874acc8fd0454f5d155754def22a599

---

kind: Service
apiVersion: v1
metadata:
  name: monolith
  namespace: ice-kream
  labels:
    app: ice-kream
    microservice: monolith
spec:
  type: ClusterIP
  selector:
    app: ice-kream
    microservice: monolith
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
