kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Name }}
  name: telem-db-pvc
  labels:
    managed_by: nectar
    app: telem-db
  finalizers: []
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Name }}
  name: telem-db
  labels:
    managed_by: nectar
    app: telem-db
spec:
  replicas: 1
  selector:
    matchLabels:
      managed_by: nectar
      app: telem-db
  template:
    metadata:
      labels:
        managed_by: nectar
        app: telem-db
    spec:
      restartPolicy: Always
      containers:
        - image: us-central1-docker.pkg.dev/nectar-bazaar/public/telem-server:1.0.0
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: {{ .Values.server_port }}
#          env:
#            - key: foo
#              value: {{ .Values.strategy }}
        - image: mongo
          name: mongodb
          ports:
            - containerPort: {{ .Values.database_port }}
          resources:  {}
          volumeMounts:
            - mountPath: /data/db
              name: telem-db-volume
      volumes:
        - name: telem-db-volume
          persistentVolumeClaim:
            claimName: telem-db-pvc

---

kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Name }}
  name: telem-db
  labels:
    managed_by: nectar
    app: telem-db
spec:
  selector:
    managed_by: nectar
    app: telem-db
  ports:
    - name: main
      port: {{ .Values.server_port }}
      targetPort: {{ .Values.server_port }}