kind: ConcernCardAdapter
id: org.concern-card-adapter.main-website
title: Website
spec:
  type: Block
  title: Website Status
  elements:
    - type: Section
      width: 1
      elements:
        - get::id::three-stat
#        - get::id::card-adapter.website.header
        - get::id::fckem
#        - get::id::fckem
#        - get::id::nukem
        - get::id::lalent

---

kind: Provider
id: lalent
source:
  type: AsyncPredicateDots
  data:
    - kind::TruePredicate
    - kind::TruePredicate
    - kind::TruePredicate
    - kind::FalsePredicate

---

kind: Provider
id: three-stat
source:
  type: ThreePartHeader
  title:
    type: Text
    text: Application Backend
    style: [bold, calm]
  subtitle:
    type: Line
    elements:
      - type: Text
        text: Workloads
      - type: StatusDots
        data: get::self>>concern=>pod_statuses
        shape: square
        spacing: 1.5px
  graphic:
    type: Icon
    name: language

---

kind: Provider
id: nukem
source:
  type: StatusDots
  spacing: 1.99px
  data:
    - name: foo
      status: positive
    - name: foo
      status: positive
    - name: foo
      status: negative
    - name: foo
      status: positive
    - name: foo
      status: positive

---

kind: Provider
id: fckem
source:
  type: Line
  elements:
    - type: Text
      #        text: "localhost:${get::self>>concern>>port_forward_spec>>pod_port}"
      text: "http://localhost:9090"
      style: [hov_underline, hov_point]
      action:
        type: port_forward
        uri:
          kind: MergeSupplier
          source:
            - get::self>>concern>>port_forward_spec>>spec
            - logo_url: get::self>>concern=>logo
    - type: Icon
      name: open_in_new
      style:
        emotion: warning2

---

kind: Provider
id: card-adapter.website.header
source:
  type: Line
  elements:
    - type: Text
      text: Workloads
      style: [bold, calm]
    - type: StatusDots
      data: get::self>>concern=>pod_statuses
      shape: square
      spacing: 1.5px

---

kind: Provider
id: card-adapter.website.memory
source:
  type: SeriesSummary
  first: graph
  style:
    mt: -10px
  data:
    kind: SeriesSummarySupplier
    humanizer: kind::BytesHumanizer
    source:
      kind: PromMatrixToSeriesSupplier
      source: get::props concern=>mem_dump

---

kind: Provider
id: card-adapter.website.cpu
source:
  type: SeriesSummary
  first: graph
  style:
    width: 100%
  data:
    kind: SeriesSummarySupplier
    humanizer: kind::CoresHumanizer
    source:
      kind: PromMatrixToSeriesSupplier
      source: get::props concern=>cpu_dump

---

kind: Provider
id: card-adapter.website.alerts
source:
  type: SeriesSummary
  first: graph
  style:
    width: 100%
  data:
    kind: SeriesSummarySupplier
    humanizer: kind::CoresHumanizer
    source:
      kind: PromMatrixToSeriesSupplier
      source: get::props concern=>cpu_dump
