deployment:
  image: us-central1-docker.pkg.dev/nectar-bazaar/public/ice-cream-app:1.0.0
  replicas: 1
  version: none
  flavor: vanilla

service:
  name: ice-cream
  port: 8080
  type: ClusterIP

quotas:
  enabled: false
  requests:
    cpu: 500m
    memory: 400Mi
  limits:
    cpu: 900m
    memory: 800Mi
