kind: Predicate
id: move-to-own-pvc.backups-enabled
title: Backup are enabled
severity: warning
message: "It is not recommended to perform database
  operations unless your databases were backed up."
type: chart-value-compare
variable: hub.backups.enabled
op: in
check_against: true