kind: ConfigurationPreset
id: provider.presets.default
title: Base Configuration Only
info: "Ships with an INSECURE database, no authentication provider,
no automation."
default: true
variables: get::kind::DefaultVariablesSupplier

---

kind: ConfigurationPreset
id: provider.presets.high-limits
title: Starter pack
info: "Insecure database, no authentication provider."
requires_further_config: true
variables:
  kind: PresetAssignmentsSupplier
  source: unsafe-database
