timeout: 20000s

substitutions:
  _IMG_FQDN: "us-central1-docker.pkg.dev/nectar-bazaar/private/desktop-client-release-mover"

images:
  - "${_IMG_FQDN}:latest"

steps:
  - id: "Pull previous"
    name: gcr.io/cloud-builders/docker
    waitFor: []
    entrypoint: "bash"
    args:
      - "-c"
      - |-
        docker pull ${_IMG_FQDN}:latest || exit 0;

  - id: "Build image"
    name: gcr.io/cloud-builders/docker
    waitFor:
      - "Pull previous"
    args:
      - "build"
      - "."
      - "--cache-from"
      - "${_IMG_FQDN}:latest"
      - "-t"
      - "${_IMG_FQDN}:latest"