kind: MockUpdate
id: nectar.mock-updates.app-update
note_url: https://raw.githubusercontent.com/eivindml/template-release-note/master/README.md
version: 2.0.0

---

kind: MockUpdate
id: nectar.mock-updates.injection
bundle:
  chart: 
    foo: bar
  inlines: 
    bar: baz

---

kind: MockUpdate
id: nectar.mock-updates.initial-injection
bundle:
  chart: {}
  inlines: {}
