kind: Concern
id: provider.publisher-frontend
cached:
  best_url:
    kind: BestSvcUrlSupplier
    source: get::props svc

  deployment:
    kind: ResourcesSupplier
    many: false
    serializer: legacy
    selector:
      res_kind: Deployment
      name: publisher-frontend

  the_svc:
    kind: ResourcesSupplier
    many: false
    serializer: legacy
    selector:
      res_kind: Service
      name: publisher-frontend

  port_forward_spec:
    kind: PortForwardSpecSupplier
    svc: get::self>>the_svc

  pod_statuses:
    kind: Supplier
    inherit: sdk.supplier.pods_in_dots_format
    pods: get::self>>deployment=>pods

---

kind: Predicate
id: predicate.publisher_frontend.all_green
title: All publisher-frontend pods running?
info: All publisher-frontend pods running?
challenge:
  kind: ResourcesSupplier
  selector:
    res_kind: Deployment
    name: publisher-frontend
  output: ternary_status
  serializer: legacy
operator: contains-only
check_against: ['positive', 'pending']
